-- testmakeidsunique.tig
Exp ((1,1),
      LetExp {letDecs = [Dec ((2,9),
                              VarDec {varName = Symbol 4, varTyp = Nothing, varInit = Exp ((2,18),IntExp 1), varEscape = False}),
                         Dec ((-1,-1),
                              FunDec [Fundec ((3,9),
                                              FundecF {funName = Symbol 5,
                                                       funParams = [Field {fieldName = Symbol 6, fieldTyp = Symbol 3, fieldEscape = False}],
                                                       funResult = Just (Symbol 3),
                                                       funBody = Exp ((3,40),
                                                                      OpExp {
                                                                         opLeft = Exp ((3,38),
                                                                                       OpExp {opLeft = Exp ((3,37),VarExp (Var ((3,37),SimpleVar (Symbol 4)))),
                                                                                              opOper = PlusOp,
                                                                                              opRight = Exp ((3,39),IntExp 1)}),
                                                                         opOper = PlusOp,
                                                                         opRight = Exp ((3,41),VarExp (Var ((3,41),SimpleVar (Symbol 6))))})})]),
                         Dec ((4,9),VarDec {varName = Symbol 7, varTyp = Nothing, varInit = Exp ((4,18),IntExp 2), varEscape = False}),
                         Dec ((-1,-1),FunDec [Fundec ((5,9),
                                                      FundecF {funName = Symbol 8,
                                                               funParams = [Field {fieldName = Symbol 9,
                                                                                   fieldTyp = Symbol 3,
                                                                                   fieldEscape = False}],
                                                               funResult = Just (Symbol 3),
                                                               funBody = Exp ((5,40),
                                                                              OpExp {opLeft =
                                                                                     Exp ((5,38),
                                                                                          OpExp {opLeft = Exp ((5,37),VarExp (Var ((5,37),SimpleVar (Symbol 7)))),
                                                                                                 opOper = PlusOp,
                                                                                                 opRight = Exp ((5,39),IntExp 1)}),
                                                                                     opOper = PlusOp,
                                                                                     opRight = Exp ((5,41),VarExp (Var ((5,41),SimpleVar (Symbol 9))))})})])],
              letBody = Exp ((6,1),SeqExp [Exp ((7,9),
                                                CallExp {callFunc = Symbol 8,
                                                         callArgs = [Exp ((7,11),VarExp (Var ((7,11),SimpleVar (Symbol 7))))]})])})
